#apiVersion: v1
#kind: ServiceAccount
#metadata:
#  name: interlink
#  namespace: vk

apiVersion: v1
kind: ServiceAccount
metadata:
  name: interlink
  namespace: vk
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: interlink-role
  namespace: vk
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  - configmaps
  - secrets
  - services
  - serviceaccounts
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - delete
  - get
  - list
  - watch
  - patch
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - create
  - get
- apiGroups:
  - ""
  resources:
  - nodes/status
  verbs:
  - update
  - patch
- apiGroups:
  - ""
  resources:
  - pods/status
  verbs:
  - update
  - patch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: interlink-rolebinding
subjects:
- kind: ServiceAccount
  name: interlink
  namespace: vk
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: interlink-role
---
apiVersion: v1
kind: Secret
metadata:
  name: interlink-secret
  namespace: vk
  annotations:
    kubernetes.io/service-account.name: interlink
  labels:
    kubernetes.io/service-account.name: interlink
type: kubernetes.io/service-account-token
