apiVersion: v1
kind: Service
metadata:
  name: ssh-listener
  namespace: jhub
spec:
  ports:
  - name: listener
    port: 8122
    protocol: TCP
    targetPort: 8122
  selector:
    app.kubernetes.io/name: ssh-fwd
  type: ClusterIP
