apiVersion: v1
kind: Service
metadata:
  name: ssh-fwd
  namespace: jhub
spec:
  ports:
  - name: ssh-fwd
    nodePort: 31022
    port: 8022
    protocol: TCP
    targetPort: 8022
  selector:
    app.kubernetes.io/name: ssh-fwd
  type: NodePort
