---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ssh-fwd
  namespace: jhub
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: ssh-fwd
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ssh-fwd
    spec:
      containers:
      - image: redis:6.2.5
        imagePullPolicy: IfNotPresent
        name: redis
        resources:
          limits:
            cpu: '1'
            memory: 1G
          requests:
            cpu: 900m
            memory: 900M
      - env:
        - name: JHUB_URL
          value: https://hub.<PUBLIC-IP>.myip.cloud.infn.it/
        image: ghcr.io/comp-dev-cms-ita/ssh-forwarder:v0.0.3
        imagePullPolicy: Always
        name: ssh-fwd
        resources:
          limits:
            cpu: '1'
            memory: 1G
          requests:
            cpu: 900m
            memory: 900M
      - env:
        - name: JHUB_URL
          value: https://hub.<PUBLIC-IP>.myip.cloud.infn.it/
        image: ghcr.io/comp-dev-cms-ita/ssh-listener:v0.0.3
        imagePullPolicy: Always
        name: listener
        resources:
          limits:
            cpu: '1'
            memory: 1G
          requests:
            cpu: 900m
            memory: 900M
