annotations:
  category: stable
apiVersion: v1
name: jhubaas
version: 4.0.1
appVersion: 2.0.1-0.dev.git.6105.hb969fa50
description: JHUBaaS Hub umbrella chart
keywords:
- jupyterhub
icon: https://jupyter.org/assets/hublogo.svg
maintainers:
- name: ttedesch
  email: tommaso.tedeschi@pg.infn.it