apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: af
resources:
  - ./release.yaml
  - ./ingress.yaml
  - ./ssh_fwd.yaml
  #- ./af-tls-secret.json

patchesStrategicMerge:
  - ./ingress.yaml

configMapGenerator:
  - name: jhub-values 
    files:
      - values.yaml=values.yaml
  - name: jhub-config
    options:
      disableNameSuffixHash: true
    files:
      - jhub_config.py=jhub_config.py
configurations:
  - kustomizeconfig.yaml